env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
    - os: osx
      language: generic
      osx_image: xcode7.3
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
      script:
        - swift build
        - swift test
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
      script:
        - swift build
        - swift test
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - pod lib lint --allow-warnings
  - set -o pipefail
  - xcodebuild test -scheme Himotoki-Mac -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
  - xcodebuild test -scheme Himotoki-iOS -configuration Release ENABLE_TESTABILITY=YES -sdk iphonesimulator | xcpretty -c
  - xcodebuild test -scheme Himotoki-tvOS -configuration Release ENABLE_TESTABILITY=YES -sdk appletvsimulator | xcpretty -c
  - xcodebuild build -scheme Himotoki-watchOS -configuration Release -sdk watchsimulator | xcpretty -c
notifications:
  email: false
